#!/usr/bin/env bash
# Description: Thiết lập 2 màn hình (Philips bên trái 0x0, AOC bên phải 1920x0, 75Hz, 1080p)
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMON_LIB="${SCRIPT_DIR}/../common.sh"
[[ -f "$COMMON_LIB" ]] && source "$COMMON_LIB"

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    check_user
fi

log_info "Bắt đầu thiết lập cấu hình màn hình cho Hyprland..."

HYPR_CONFIG_DIR="${HOME}/.config/hypr/config"
mkdir -p "$HYPR_CONFIG_DIR"

VARIABLES_FILE="${HYPR_CONFIG_DIR}/variables.lua"
MONITORS_FILE="${HYPR_CONFIG_DIR}/monitors.lua"
WORKSPACES_FILE="${HYPR_CONFIG_DIR}/workspaces.lua"

# 1. Cập nhật biến màn hình trong variables.lua
log_info "Cập nhật định danh màn hình trong variables.lua..."
if [[ -f "$VARIABLES_FILE" ]]; then
    # Thay thế hoặc cập nhật biến MONITOR1 và MONITOR2
    sed -i -E 's/^MONITOR1[[:space:]]*=.*/MONITOR1 = "HDMI-A-2" -- Philips (Left)/' "$VARIABLES_FILE"
    sed -i -E 's/^MONITOR2[[:space:]]*=.*/MONITOR2 = "DP-2"     -- AOC (Right)/' "$VARIABLES_FILE"
    sed -i -E 's/^PRIMARY_MONITOR[[:space:]]*=.*/PRIMARY_MONITOR = MONITOR1/' "$VARIABLES_FILE"
else
    cat <<'EOF' > "$VARIABLES_FILE"
MONITOR1 = "HDMI-A-2" -- Philips (Left)
MONITOR2 = "DP-2"     -- AOC (Right)
MONITOR3 = ""
PRIMARY_MONITOR = MONITOR1
NUM_WPM = 3
EOF
fi

# 2. Cấu hình monitors.lua: vị trí, độ phân giải tối đa (1080p) và tần số quét tối đa (74.97Hz)
log_info "Cấu hình độ phân giải và vị trí trong monitors.lua..."
cat <<'EOF' > "$MONITORS_FILE"
-- Cấu hình hiển thị đa màn hình (Auto-generated by setup script)
-- Monitor 1: Philips (bên trái, vị trí 0x0, 75Hz, 1080p)
hl.monitor({
    output    = MONITOR1,
    mode      = "1920x1080@74.97",
    position  = "0x0",
    scale     = "1",
})

-- Monitor 2: AOC (bên phải, vị trí 1920x0, 75Hz, 1080p)
hl.monitor({
    output    = MONITOR2,
    mode      = "1920x1080@74.97",
    position  = "1920x0",
    scale     = "1",
})

-- Fallback cho màn hình phụ khác cắm thêm
hl.monitor({
    output    = "",
    mode      = "preferred",
    position  = "auto",
    scale     = "auto",
})
EOF

# 3. Phân bổ Workspace cho từng màn hình
log_info "Cấu hình phân bổ workspace cho 2 màn hình trong workspaces.lua..."
if [[ -f "$WORKSPACES_FILE" ]]; then
    # Bỏ comment các rule workspace 4, 5, 6 cho MONITOR2
    sed -i 's/^--[[:space:]]*\(hl\.workspace_rule({ workspace = "[456]", monitor = MONITOR2.*\)/\1/' "$WORKSPACES_FILE"
fi

# 4. Áp dụng ngay nếu Hyprland đang chạy
if pgrep -x "Hyprland" >/dev/null 2>&1; then
    log_info "Đang reload Hyprland để áp dụng thiết lập màn hình ngay..."
    hyprctl reload >/dev/null 2>&1 || true
fi

log_success "Thiết lập màn hình hoàn tất: Philips (Trái: 0x0) và AOC (Phải: 1920x0) @ 1080p 75Hz."
